[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
markers =
    login: login test cases
    irctc: IRCTC related tests
    pnr_status: PNR status test cases
    train_search: train search test cases
    search: search test cases
    smoke: smoke test cases
    regression: regression test cases
addopts =
    -v
    --html=reports/html/report.html
    --self-contained-html
    --alluredir=reports/allure-results

